### ISSUE TITLE
macOS 13.2.1下部分数字未显示为提瓦特风格？

### ISSUE THREAD

**Issue by PrussianBlueCN** [SpeedyOrc-C/Hoyo-Glyphs#10]
<img width="450" alt="image" src="https://user-images.githubusercontent.com/110645427/220833578-90353701-d4b6-45d2-92a8-3e5830a78a34.png">

**Comment by Yunru-1314** [comment]
因为就没有相应文字，5到9在游戏里都没有，所以就没做
