### ISSUE TITLE
Star Rail Neue 似乎不支持特殊字符

### ISSUE THREAD

**Issue by 188102836** [SpeedyOrc-C/HoYo-Glyphs#14]
```
<>?/;\:|"{}[]-_=+`~
```
这些字符都无法显示，是忘了做还是有意而为之

![image](https://github.com/SpeedyOrc-C/HoYo-Glyphs/assets/69347367/cfe7f6a4-6912-4b7e-8cf3-2db6545f0b22)

**Comment by 188102836** [comment]
这是字体：

![image](https://github.com/SpeedyOrc-C/HoYo-Glyphs/assets/69347367/0b8b9475-e92f-46d8-970e-f43b8b11fa9f)

**Comment by Yunru-1314** [comment]
你的字体编码选对了吗，字体编码选择错误会导致显示乱码（因为软件读取编码错误）

**Comment by SpeedyOrc-C** [comment]
因为游戏里只出现了逗号`,`、句号`.`和傻瓜单引号`'`，其他的符号是没有的。如果您输入了一个没有的字符，那就会显示成一个框框，里面有一个大写字母B的样子。

那个符号在低分辨率下看起来确实很糊，您可以将字号放大，或者使用更清晰的屏幕。这样就不会把那个符号看成乱码了。

**Comment by 188102836** [comment]
> 因为游戏里只出现了逗号`,`、句号`.`和傻瓜单引号`'`，其他的符号是没有的。如果您输入了一个没有的字符，那就会显示成一个框框，里面有一个大写字母B的样子。
> 
> 那个符号在低分辨率下看起来确实很糊，您可以将字号放大，或者使用更清晰的屏幕。这样就不会把那个符号看成乱码了。

好的，所以是因为游戏内没有吗？不过这样的话这些符号就分辨不出来了，因为它们在这个字体下显示的是一样的。

顺便问一句，这个符号是从哪里来的呢？

**Comment by SpeedyOrc-C** [comment]
傻瓜单引号在贝罗伯格下层区的招牌上可以看到，逗号和句号可以在黑塔空间站看到。

**Comment by 188102836** [comment]
没说清楚，我指的是最开始那些字符

**Comment by SpeedyOrc-C** [comment]
@188102836 不好意思，过了这么久才回复。最开始的那些字符是我自己画的一个用来代替未知字符的符号。其实就是一个长方形，里面加一个星穹铁道文的大写字母 B。因为在游戏的设置界面里面调语言的时候，那个标签的图标也画的是字母 B。
