### ISSUE TITLE
关于枫丹字母

### ISSUE THREAD

**Issue by Yunru-1314** [SpeedyOrc-C/HoYo-Glyphs#15]
请问作者有无绘制枫丹字母的打算？
如果有，那我等待就好（不急）；
没有就算了，毕竟费时费力（这p活不做也罢）。

**Comment by SpeedyOrc-C** [comment]
有打算的，目前已经做了一个字母了。因为我最近在做人物关系图，所以做字体就先放一放。

**Comment by Yunru-1314** [comment]
> 有打算的，目前已经做了一个字母了。因为我最近在做人物关系图，所以做字体就先放一放。

字母在做了就行（，不过这关系图是什么的人物关系图？方便了解一下么（

**Comment by SpeedyOrc-C** [comment]
最终效果：[关系图](rel.teyvatlore.com/app)

[GitHub 仓库](https://github.com/SpeedyOrc-C/Irminsul)

**Comment by Yunru-1314** [comment]
> 最终效果：[关系图](https://rel.teyvatlore.com/app)
> 
> [GitHub 仓库](https://github.com/SpeedyOrc-C/Irminsul)

![-35ba47209140be34.jpg](https://github.com/SpeedyOrc-C/HoYo-Glyphs/assets/103897810/57fb44d5-4771-4bc5-8b56-bae0b63e40e4)

我看着前些天泄露出来的设计稿里夏洛蒂那张图片上有部分枫丹的字母，您看您需要不？
