### ISSUE TITLE
Packaged Download 打包下载

### ISSUE THREAD

**Issue by CNChestnut** [SpeedyOrc-C/HoYo-Glyphs#17]
When downloading, it seems that all files can only be downloaded individually, not packaged together.
在下载时，所有文件似乎只能单独下载，而不能一起打包下载。

Also the files are spread across `Repository` and `Release` and are not harmonized.
而且文件分布在`仓库`和 `Release` 中，并不统一。

还有就是就算这样，仓库内下载链接也可以指向 raw.githubuserconnect.com 而不是到 files 在让用户点下载

**Comment by CNChestnut** [comment]
本来想着 `git clone` 的，但是崩铁的字体怎么只在 Release 里面

**Comment by CNChestnut** [comment]
好吧我搞错了，下载的都是从 Release 的，但是还是太分散了。: )

**Comment by CNChestnut** [comment]
还有就是就算这样，下载链接也可以指向 raw 而不是到 files 在让用户点下载

**Comment by SpeedyOrc-C** [comment]
确实很纠结，每次发布到底是要把所有字体一起打包发布还是一个一个发布，如果全部打包发布就省事多了。到时候这个东西完结的时候再把工程文件传上去。

**Comment by CNChestnut** [comment]
我暂时做了这个 https://github.com/CNChestnut/Packaged_HoYo-Glyphs

**Comment by SpeedyOrc-C** [comment]
不好意思，刚刚放假，之前没时间看。

我明白你的意思了。现在我大概已经整理好了，以后的字体全部都一起打包发布吧，也不用天天更新那个鬼 README 了。你看看这样的文件夹结构如何？如果顺眼的话我等下就发了。

<img width="1008" alt="image" src="https://github.com/user-attachments/assets/74ae44d6-8aa1-4b73-af1c-2046303a46c2">

**Comment by CNChestnut** [comment]
可以啊，不过这个其实不需要咨询我的意见吧。

**Comment by SpeedyOrc-C** [comment]
我的意思是，打包发布有可能反而会加大下载的难度，因为会有人看不懂字体名代表什么文字。

**Comment by 98ColdDew** [comment]
你好！我发现无论是直接下载 repository 还是去 Releases 下载 Source code.，font 文件夹一直没有更新过，一直只有原神到须弥沙漠为止的字体。我现在只能在 Releases 中找 Source code 上面每次更新的单个字体下载。不知道是我下载的姿势不对还是什么情况，希望可以看一下这个问题谢谢！

**Comment by 98ColdDew** [comment]
哦，我又看了一下 readme 。就是说，之前为了节省空间， repository 本来就没有打算每次更新对吗？那没事了（

那题主说的不能一起打包下载确实是一个问题。然后你回复说以后会更新打包的，但是最新的07.14版本里还是没有……

所以还是下一次更新才开始打包么（笑

**Comment by 98ColdDew** [comment]
之前没细看就发的评论已删，现在就一个问题了：2024.07.14版本的仓库依然是只有原神到须弥沙漠为止的字体，没有枫丹、铁、绝等新字体，打包下载仍不支持。希望有时间的话可以检查更新一下，谢谢

**Comment by CNChestnut** [comment]
看来我 [这个](https://github.com/CNChestnut/Packaged_HoYo-Glyphs) 还是有维护的必要。hh

还有 #17 这问题作者有头绪吗。
