### ISSUE TITLE
Can the Genshin Impact wiki on Fandom.com use these fonts?

### ISSUE THREAD

**Issue by rjwut** [SpeedyOrc-C/HoYo-Glyphs#20]
It would be helpful to use these fonts in articles on the Genshin Impact wiki, but I couldn't find any license the describes how the fonts can be used.

**Comment by SpeedyOrc-C** [comment]
Just updated the license! Here are the rules:

1. Not for any forms of commercial use.
2. Provide a link to this repository for all media (e.g. websites) that embed any fonts from this repository.
3. Modified fonts should not be made close-sourced.
4. If the embedded fonts are the modified version, provide a link to where they come from.
5. All modified fonts should provide a link to their unmodified version, that is, forming a closure of dependency.
