### ISSUE TITLE
发布的文件里有大量_MACOSX、._.DS_Store等无关文件

### ISSUE THREAD

**Issue by YexuanXiao** [SpeedyOrc-C/HoYo-Glyphs#21]
rt

**Comment by heckerpowered** [comment]
可以尝试使用下列命令使系统不再生成.DS_Store
defaults write com.apple.desktopservicesDSDontWriteNetworkStores true

或者是在.gitignore中加入
```
# macOS Cache
.DS_Store
```

**Comment by SpeedyOrc-C** [comment]
这个文件我还是得留着，因为我要在访达里面按文件类型排序，所以发布的时候手动排除一下就好了。

**Comment by SpeedyOrc-C** [comment]
Release 已更新。

**Comment by YexuanXiao** [comment]
@SpeedyOrc-C 现在还是有_MACOSX文件夹以及里面的大量文件
