### ISSUE TITLE
字体名称的更迭演变

### ISSUE THREAD

**Issue by 98ColdDew** [SpeedyOrc-C/HoYo-Glyphs#23]
你好！感谢大佬的辛苦制作，但是本人发现很多字体名称经过变更，能否在wiki的更新记录中对此进行解释说明（迫切），谢谢。（尤其是最近的原神字体名称几乎都有更改）如果以后还会有多次演变，希望能汇总一下字体名称变更的版本表（非迫切），感谢

**Comment by 98ColdDew** [comment]
比如：

1.002 Deshret Neue
1.005 Deshret Inscription

1.000 Fonte Ainee
2.000 Font Ainee

1.000 Inazuma Neue
1.001 Inazuma Brush

0.007 Sumeru Neue
1.000 Sumeru Scribe

**Comment by SpeedyOrc-C** [comment]
枫丹的那个会改是因为之前把单词拼错了。其他的名字改了是因为很久很久之前就已经定好了，准备在一次更新中全部改好。不过话说为啥您会在意字体的名字呢？

**Comment by 98ColdDew** [comment]
感谢您的解答，在意名字是因为我有在别的游戏中制作字体MOD，字体的名称有部分地参考您的命名：
https://steamcommunity.com/sharedfiles/filedetails/?id=3044285842

**Comment by 98ColdDew** [comment]
如果字体名称多次更改，我的字体MOD就只能考虑保持单独命名，而不同步了

**Comment by SpeedyOrc-C** [comment]
其实您可以自己决定它们在 mod 里面应该叫啥，如果怕别人看不懂，可以用国家名来命名。

**Comment by 98ColdDew** [comment]
好吧，感谢
