### ISSUE TITLE
烟绯六命额外增加一枚丹火印，可以得到数字4

### ISSUE THREAD

**Issue by Neutralization** [SpeedyOrc-C/Hoyo-Glyphs#6]
<img width="598" alt="Snipaste_2022-07-30_21-59-15" src="https://user-images.githubusercontent.com/50076677/181917842-0f15ae7b-22e2-47f0-a2c1-7e6810d72d21.png">

**Comment by SpeedyOrc-C** [comment]
非常感谢！这个图看起来相当清晰。
