### ISSUE TITLE
字体演示有个bug

### ISSUE THREAD

**Issue by BigGodKang** [SpeedyOrc-C/Hoyo-Glyphs#7]
在试前瞻PV散兵的iseeyou时发现u对应的须弥雨林字符无法显示
![QQ截图20220916214400](https://user-images.githubusercontent.com/112635514/190653260-0adc089e-f531-42f1-a7f3-7552c6731c20.png)

**Comment by BigGodKang** [comment]
但是u对应的那个符号官号发的视频里已经有了呀（

**Comment by SpeedyOrc-C** [comment]
其实 U 在 PV 发出之前就已经有了，由于画面不清晰，所以一直等到现在才做。
