### ISSUE TITLE
关于绝区零

### ISSUE THREAD

**Issue by Yunru-1314** [SpeedyOrc-C/Hoyo-Glyphs#8]
请问有没有绝区零的操作界面文字，我感觉那个是调用系统的文字😂

**Comment by SpeedyOrc-C** [comment]
游戏里电脑上的文字都是一号变体吧。

**Comment by Yunru-1314** [comment]
> 游戏里电脑上的文字都是一号变体吧。

我指的是这个界面的文字
![IMG_20221017_152743_1.jpg](https://user-images.githubusercontent.com/103897810/196114876-66310509-c5bb-4d23-8ed1-b62e1b8ff911.jpg)
这个应该是调用的系统内置的ttf文件吧

**Comment by Yunru-1314** [comment]
比如这个是原神操作界面的字体
![image](https://user-images.githubusercontent.com/103897810/196116931-584e83ec-7688-41ca-9f5f-db9358c5fef6.png)
这个是星穹铁道的
![image](https://user-images.githubusercontent.com/103897810/196117059-eb9337db-1232-4e1e-980a-39bf2986344d.png)

**Comment by SpeedyOrc-C** [comment]
绝区零用的是“印品鸿蒙体”，而且这三款游戏都没有调用系统字体，都是内嵌的。您发的星穹铁道的西文部分长得不太像。

<img width="561" alt="image" src="https://user-images.githubusercontent.com/40349377/196117306-f4e142d8-1adf-48ff-a4ba-e7c63a3b5e85.png">

**Comment by Yunru-1314** [comment]
> 绝区零用的是“印品鸿蒙体”，而且这三款游戏都没有调用系统字体，都是内嵌的。您发的星穹铁道的西文部分长得不太像。
> 
> <img width="561" alt="image" src="https://user-images.githubusercontent.com/40349377/196117306-f4e142d8-1adf-48ff-a4ba-e7c63a3b5e85.png">
> 

这个星穹铁道的字体我是到游戏根目录里找到的，这个应该是星穹铁道的游戏内公告和抽卡记录调用的字体，应该没问题的

**Comment by Yunru-1314** [comment]
> 绝区零用的是“印品鸿蒙体”，而且这三款游戏都没有调用系统字体，都是内嵌的。您发的星穹铁道的西文部分长得不太像。
> 
> <img width="561" alt="image" src="https://user-images.githubusercontent.com/40349377/196117306-f4e142d8-1adf-48ff-a4ba-e7c63a3b5e85.png">
> 

那您这个字体文件能发我一份吗，谢谢

**Comment by SpeedyOrc-C** [comment]
按照规定，我不能直接发，需要到[这里](https://www.17font.com/font/detail/a049701dbe5f451d82e7c5b78a88d6d4.html)购买非商用授权。
