### ISSUE TITLE
关于可能的小改进

### ISSUE THREAD

**Issue by Wenti-D** [SpeedyOrc-C/HoYo-Glyphs#9]
我之前也没事做了一些提瓦特文字 ~~（如有需要可以去我仓库看看）~~，在这里提一些小建议与问题：
- 提瓦特通用语「太挤」，游戏中文字的字距是很宽的。
- 稻妻文目前缺字母 P，可以参考我的（不一定对）。
- 游戏中稻妻文可以纵书，有没有这方面的适配？
- 建议添加字距微调，特别是提瓦特通用语，否则有时看起来间距不一。
![image](https://user-images.githubusercontent.com/73067578/215426531-220c1222-f182-4a03-a464-d9bcfffbb9c1.png)
![image](https://user-images.githubusercontent.com/73067578/215426670-61ba6706-32ac-4d67-b63a-a487cb636a09.png)
- 「01234」放在提瓦特通用语似乎有待商榷，我觉得这数字是给玩家看的，而不是给提瓦特大陆看的。

顺便问一下能否借用须弥部分的字形去扩充我的字体库呢？感激不尽。

**Comment by SpeedyOrc-C** [comment]
通用文字的宽度就不理了，自己可以想调多宽就调多宽。
其他人也在催字母 P，也有很多人已经找出了字形。
**可以加入竖排文本。**
不是很有时间调通用文的字距。
把数字加进去的原因是，数字的风格和通用文的风格一致。
**可以拿须弥文去扩充。**

**Comment by SpeedyOrc-C** [comment]
您的仓库在很久之前就已经看过啦~

**Comment by SpeedyOrc-C** [comment]
@Wenti-D 
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/40349377/216734699-f1cf5ec9-92e0-4483-98b8-82492b494cb3.png">

我下载了您做的那个，然后试着用 LibreOffice 竖着排，发现并没有转过来。请问具体应该调什么地方呢？

**Comment by Wenti-D** [comment]
> @Wenti-D <img alt="image" width="1792" src="https://user-images.githubusercontent.com/40349377/216734699-f1cf5ec9-92e0-4483-98b8-82492b494cb3.png">
> 
> 我下载了您做的那个，然后试着用 LibreOffice 竖着排，发现并没有转过来。请问具体应该调什么地方呢？

我是把竖排文本作为一个 Opentype 特性来提供的，在我的示例图片里可见字体名称后面附加了 `:vert` 以启用特性。

**Comment by Wenti-D** [comment]
发现赤王文字中：
- P 左上角不是三角形，是扇形；
- S 最上面一画有明显的抬升，而非水平。
![image](https://user-images.githubusercontent.com/73067578/218136528-8e539f6a-d174-4d09-bec6-e8868ee3d650.png)
这些字形是从元能尖碑上「拓印」下来的。

**Comment by SpeedyOrc-C** [comment]
已经改好了，话说真的有人会注意到吗。

**Comment by Wenti-D** [comment]
B 站上倒是有《把宋体放大 100 倍会看到什么？》的视频（笑）

**Comment by Yunru-1314** [comment]
> 发现赤王文字中：
> - P 左上角不是三角形，是扇形；
> - S 最上面一画有明显的抬升，而非水平。
> ![image](https://user-images.githubusercontent.com/73067578/218136528-8e539f6a-d174-4d09-bec6-e8868ee3d650.png)
> 这些字形是从元能尖碑上「拓印」下来的。
> 

我愿称你为列文虎克xD

**Comment by SpeedyOrc-C** [comment]
改好的赤冠字母现在可以下载了。

**Comment by SpeedyOrc-C** [comment]
@Wenti-D 正在重新一个个调提瓦特文的字偶距。

**Comment by Wenti-D** [comment]
请问一下赤沙文的 J、Q、U、Y 是从哪里获得的呢？现在我就差这四个没找到来源了……

**Comment by Etymodes** [comment]
@Wenti-D 你好，在镀金旅团的厄灵及武器上有J的形状。U和在元能尖碑上能找到，Y在须弥沙漠角色的立绘背景里有。在这四个字母上还有问题可以私下联系我。

**Comment by abzulyc** [comment]
@SpeedyOrc-C 星穹文字好像缺少大写Q和小写j，这两个打出来都是正常英语字典里也找不到，是游戏里还没有出现吗

**Comment by Wenti-D** [comment]
> @Wenti-D 提瓦特通用文的字偶距已经重新调整过，这下满意了吧。

我以为您会适时关闭这个议题的来着……
